---

# Main collection of env. vars to set for all tasks and scripts.
env:
    ####
    #### Cache-image names to test with (double-quotes around names are critical)
    ####
    FEDORA_NAME: "fedora-40"
    FEDORA_AARCH64_NAME: "${FEDORA_NAME}-aarch64"

    # Image identifiers
    IMAGE_SUFFIX: "c20241016t144444z-f40f39d13"

    # EC2 images
    FEDORA_AMI: "fedora-aws-${IMAGE_SUFFIX}"
    FEDORA_AARCH64_AMI: "fedora-podman-aws-arm64-${IMAGE_SUFFIX}"
    WINDOWS_AMI: "win-server-wsl-${IMAGE_SUFFIX}"

    # Container
    FEDORA_CONTAINER_FQIN: "quay.io/libpod/fedora_podman:${IMAGE_SUFFIX}"

    # directory where the images will be placed
    OUTDIR: "outdir"

    HOME: /root
    CIRRUS_WORKING_DIR: /var/tmp/podman-machine-os

aws_credentials: ENCRYPTED[b01991b35fe3f81eed974cf47b5541ed518eacfee4e430e9fb50fba31090f557ea86b0b79b5f5b4a712218206e0f3f58]

# Default timeout
timeout_in: 30m

image_build_task:
    name: "Image Build ${ARCH}"
    alias: "image_build"
    ec2_instance:
        image: "${VM_IMAGE}"
        type: "${EC2_INST_TYPE}"
        region: us-east-1
    matrix:
        - env:
            ARCH: "x86_64"
            VM_IMAGE: "${FEDORA_AMI}"
            EC2_INST_TYPE: "m5zn.metal"  # Bare-metal instance is required
        - env:
            ARCH: "aarch64"
            VM_IMAGE: "${FEDORA_AARCH64_AMI}"
            EC2_INST_TYPE: "c6g.metal"  # Bare-metal instance is required

    setup_script: ./contrib/cirrus/setup.sh
    build_script: ./build.sh
    verify_script: ./contrib/cirrus/verify.sh
    image_prep_script: "mv $OUTDIR/*.zst ."
    image_artifacts: &image_artifacts
        path: "*.zst"
        type: application/octet-stream

verify_windows_task:
    name: "Verify HyperV"
    alias: "verify_windows"
    depends_on:
        - image_build
    ec2_instance: &windows
        image: "${WINDOWS_AMI}"
        type: m5zn.metal
        region: us-east-1
        platform: windows
    env:
        ARCH: "x86_64"
        CIRRUS_WORKING_DIR: "${LOCALAPPDATA}\\cirrus-ci-build"
        CIRRUS_SHELL: powershell
        PATH: "${PATH};C:\\Program Files\\RedHat\\Podman"
        MACHINE_IMAGE: "stage-machine-os.${ARCH}.hyperv.vhdx.zst"
        MACHINE_IMAGE_URL: "https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/Image Build ${ARCH}/image/${MACHINE_IMAGE}"
        PODMAN_VERSION: 5.2.5
    setup_script: .\contrib\cirrus\windows_setup.ps1
    main_script: |
        $Env:CONTAINERS_MACHINE_PROVIDER = "hyperv"
        $Env:MACHINE_IMAGE_PATH="..\${ENV:MACHINE_IMAGE}"
        .\bin\ginkgo .\verify
        if ( ($LASTEXITCODE -ne $null) -and ($LASTEXITCODE -ne 0) ) {
            throw "Exit code = '$LASTEXITCODE' running ginkgo"
        }

test_task:
    name: "Total Success"
    alias: success
    depends_on:
        - image_build
        - verify_windows
    container:
        image: "${FEDORA_CONTAINER_FQIN}"
        cpu: 1
        memory: 1
    noop_script: true
