---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

jobs:
  # All tests specified in the `/plans/` subdir
  - job: tests
    trigger: pull_request
    skip_build: true
    notifications:
      failure_comment:
        message: "container build test failed. @containers/packit-build please check."
    targets:
      - fedora-rawhide
    identifier: build_container_test
    tmt_plan: "/plans/build_container_test"
